config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#show'
  get 'myfavorite', to: 'users#myfavorite'

  resources :photoposts do
    member do
      put 'like', to: "photoposts#upvote"
    end
  end

  resources :users do
    resources :photoposts
  end

  resources :sessions

  root 'photoposts#index'

end

app/models/photopost.rb
class Photopost < ActiveRecord::Base
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def already_likes?(photopost)
    self.likes.where(:all, :conditions => ['photopost_id = ?', photopost.id]).size > 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  has_secure_password
  has_many :photoposts

  validates_uniqueness_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

def authorize
  redirect_to login_url, alert: "Not authorized" if current_user.nil?
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/photoposts_controller.rb
class PhotopostsController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :new ]
  before_action :set_photopost, only: [:edit, :update, :upvote, :destroy]
  before_action :set_user

  def new
    @photopost = current_user.photoposts.build
  end

  def index
    @photoposts = Photopost.all
  end

  def show

  end

  def edit
  end

  def upvote
    @photopost.upvote_by current_user
    redirect_to :back
  end


  def destroy
    @photopost.destroy
    respond_to do |format|
      format.html { redirect_to '/profile', notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
    if @photopost.update(photopost_params)
        format.html { redirect_to '/profile', :notice => 'Photo was successfully updated.' }
        format.json { render :json => @photopost, :status => :ok, :location => @photopost }
      else
        format.html { render :edit }
        format.json { render :json => @photopost.errors, :status => :unprocessable_entity }
      end
    end

    end

  def create
    @photopost = current_user.photoposts.build(photopost_params)
    respond_to do |format|
      if @photopost.save
        format.html { redirect_to '/profile', :notice => 'Photo was successfully created.' }
        format.json { render :json => @photopost, :status => :created, :location => @photopost }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photopost.errors, :status => :unprocessable_entity }
      end
    end
    end


    private

  def set_user
    @user = current_user
  end

  def set_photopost
    @photopost = Photopost.find(params[:id])
  end

    def photopost_params
      params.require(:photopost).permit( :image, :title, :url )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :show]
  before_action :set_photoposts, only: [:show]

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end


  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end


  def show
      @user = current_user
  end

  def update

  end

  def myfavorite
    @user = current_user
    @photoposts = @user.find_up_voted_items
  end

  private

  def set_photoposts
    @photoposts = current_user.photoposts
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photoposts_helper.rb
module PhotopostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>NYPins</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav class="navbar navbar-light bg-faded">
    <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
      &#9776;
    </button>
    <ul class="nav navbar-nav">
      <% if current_user %>
          <li class="pull-xs-right" id="loged"> Logged in as <%= current_user.name %>.</li>
          <li> <%= link_to "Log Out", logout_path, class: 'pull-xs-right' %></li>
      <% else %>
          <li> <%= link_to "Sign Up", signup_path, class: 'pull-xs-right', id: 'loged' %></li>
          <li> <%= link_to "Log In", login_path, class: 'pull-xs-right' %></li>
      <% end %>
    </ul>

    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <a class="navbar-brand" href="/photoposts">NYPins</a>
      <ul class="nav navbar-nav">
        <li class="nav-item ">
          <a class="nav-link " href="/photoposts">Photoposts</a>
        </li>
        <li class="nav-item">
         <a class="nav-link " href='/profile'>Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href='/myfavorite'>Favorites</a>
        </li>
      </ul>
    </div>
  </nav>
</header>
<div class="container">
  <%flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
</div>

<%= yield %>



</body>
</html>

app/views/pages/about.html.erb
<div class="container-fluid">
  <h1>About</h1>
  <p>This is the about page</p>
</div>

app/views/pages/contact.html.erb
<div class="container-fluid">
  <h1>Contact</h1>
  <p>This is the contact page</p>
</div>

app/views/pages/home.html.erb
<div class="container-fluid">
<h1>Home</h1>
<p>This is the Home page</p>
</div>

app/views/photoposts/_form.erb
<%= form_for @photopost, :html => { :multipart => true } do |f| %>
    <% if @photopost.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@photopost.errors.count, "error") %> prohibited this contact from being saved:</h2>

          <ul>
            <% @photopost.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
     <%= f.file_field :image %>
    </div>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :url %><br>
      <%= f.url_field :url %>
    </div>
    <button class = 'btn btn-primary'><%f.submit %>Submit</button>

<% end %>

app/views/photoposts/edit.html.erb
<div class="container">
  <h1>Edit</h1>

  <%= render 'form' %>

  <%= link_to 'Back', :back %>

</div>

app/views/photoposts/index.html.erb
<div class="container">

  <div id="photopost" class = "transitions-enabled">
  <h1>Photos</h1>
  <div class="card-columns">
  <% @photoposts.each do |photopost| %>


      <div class="card">
        <%= image_tag photopost.image.url(:medium), class: 'card-img-top' %>
      <div class="card-block">
       <h2 class="card-title"><%= photopost.title %></h2>
        <strong class="user">From: <%= photopost.user.email %></strong>
       <p class="card-text"><%= photopost.url %></p>
        <%= button_to like_photopost_path(photopost.id), method: :put,  class: 'btn btn-primary btn-sm'  do %>
        <i class="fa fa-heart-o"><%=" " + photopost.get_upvotes.size.to_s %></i>
        <% end %>
     </div>
  </div>
  <% end %>
  </div>
</div>
</div>

app/views/photoposts/new.html.erb
<div class="container">
  <h1>New Photo</h1>

  <%= render 'form' %>

  <%= link_to 'Home', '/pages/home' %>
</div>

app/views/photoposts/show.html.erb
<div class="container">
  <h1>My Photos</h1>

  <% @photoposts.each do |photopost| %>

      <div class="photopost">

        <h3><%= photopost.title %></h3>
        <strong>From: <%= photopost.user.email %></strong>
        <p><%= photopost.url %></p>
        <%= link_to 'Edit', edit_photopost_path(photopost.id) %>
        <%= link_to 'Destroy', photopost, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>


  <% end %>

</div>

app/views/users/_form.html.erb
<%= form_for @user  do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this contact from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>

    <button class = 'btn btn-primary'><%f.submit %>Submit</button>

<% end %>

app/views/users/myfavorite.html.erb
<div class="container">
  <h1>My Favorite</h1>

  <strong><%=@user.name %></strong>

  <div id="photopost" class = "transitions-enabled">

<div class="card-columns">
  <% @photoposts.each do |photopost| %>

      <div class="card">
        <%= image_tag photopost.image.url(:medium), class: 'card-img-top' %>
        <div class="card-block">
          <h2 class="card-title"><%= photopost.title %></h2>
          <strong class="user">From: <%= photopost.user.email %></strong>
          <p class="card-text"><%= photopost.url %></p>
          <%= button_to like_photopost_path(photopost.id), method: :put,  class: 'btn btn-primary btn-sm'  do %>
              <i class="fa fa-heart-o"><%=" " + photopost.get_upvotes.size.to_s %></i>
          <% end %>
        </div>
      </div>
  <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <h1>Signup</h1>

          <%= render 'form' %>

          <%=link_to 'Home', 'pages/home' %>

  </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container">
  <h1>Profile</h1>

  <strong><%=@user.name %></strong>
  <p><%=@user.email %></p>

  <div id="photopost" class = "transitions-enabled">

  <h2>My Photos</h2>

  <%= link_to 'Add Photo', new_user_photopost_path(@user)%>
    <%= link_to 'My Favorite', '/myfavorite' %>

  <div class="card-columns">
    <% @photoposts.each do |photopost| %>

        <div class="card">
          <%= image_tag photopost.image.url(:medium), class: 'card-img-top' %>
          <div class="card-block">
            <h2 class="card-title"><%= photopost.title %></h2>
            <strong class="user">From: <%= photopost.user.email %></strong>
            <p class="card-text"><%= photopost.url %></p>
            <%= button_to like_photopost_path(photopost.id), method: :put,  class: 'btn btn-primary btn-sm'  do %>
                <i class="fa fa-heart-o"><%=" " + photopost.get_upvotes.size.to_s %></i>
            <% end %>
          </div>
          <%= link_to 'Edit', edit_user_photopost_path(photopost.user_id, photopost.id) %>
          <%= link_to 'Destroy', user_photopost_path(photopost.user_id, photopost.id),  method: :delete,   data: { confirm: 'Are you sure?' } %>

        </div>
    <% end %>
  </div>
  <%=link_to 'Home', '/pages/home' %>
</div>